[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Milkyway Quasar <azit.ghising#gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = {version = "0.8.9", features = ["form"]}
tokio = {version = "1.53.1", features = ["full"]}
reqwest = {version = "0.13.4"}
serde = {version = "1.0.229", features = ["derive"]}
config = "0.13"
uuid = {version = "1", features = ["v4"]}
chrono = "0.4.15"
urlencoding = "2"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
